---
apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend-nodeport
  namespace: area51-website
  labels:
    app: area51-web-front
spec:
  type: NodePort
  selector:
    app: area51-web-front
  ports:
  - port: 80
    nodePort: 30004
    protocol: TCP
    name: frontend

