# Common vars
availability_zone: melbourne-qh2-uom

# K3s version
k3s_version: "v1.21.0+k3s1"

# Volume
volumes:
  - vol_name: couchdb-1
    vol_size: 50
  - vol_name: couchdb-2
    vol_size: 50
  - vol_name: couchdb-3
    vol_size: 50
  - vol_name: registry
    vol_size: 50

security_groups:
  - name: cluster
    internal: true
    description: "Allows all traffic between nodes"
    remote_group: cluster
  - name: services
    internal: false
    description: "Security group for external access to admin interface, web app, and docker registry"
    protocol: tcp
    port_range_min: 30001
    port_range_max: 30004
    remote_ip_prefix: 0.0.0.0/0
  - name: k3s api
    internal: false
    description: "Security group for k3s api"
    protocol: tcp
    port_range_min: 6443
    port_range_max: 6443
    remote_ip_prefix: 0.0.0.0/0

# Instance
masters:
  - name: master-1
    volumes: ['couchdb-1']
    security_groups: ['cluster', 'ssh', 'http', 'k3s api', 'services']
  - name: master-2
    volumes: ['couchdb-2']
    security_groups: ['cluster', 'ssh', 'http', 'k3s api', 'services']
  - name: master-3
    volumes: ['couchdb-3']
    security_groups: ['cluster', 'ssh', 'http', 'k3s api', 'services']
init:
  volumes: ['registry']
  security_groups: ['cluster', 'ssh', 'http', 'k3s api', 'services']

instance_image: NeCTAR Ubuntu 20.04 LTS (Focal) amd64
instance_key_name: Area51
local_key_path: ~/.ssh/area51

init_flavor: uom.mse.1c4g
master_flavor: uom.mse.2c9g
