---
apiVersion: v1
kind: Service
metadata:
  name: webapp-backend-nodeport
  namespace: area51-website
  labels:
    app: area51-web-back
spec:
  type: NodePort
  selector:
    app: area51-web-back
  ports:
  - port: 5000
    nodePort: 30003
    protocol: TCP
    name: backend
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-frontend-nodeport
  namespace: area51-website
  labels:
    app: area51-web-front
spec:
  type: NodePort
  selector:
    app: area51-web-front
  ports:
  - port: 80
    nodePort: 30004
    protocol: TCP
    name: frontend
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: area51-webapp
#  namespace: area51-website
#  labels:
#    app: area51-web
#spec:
#  type: LoadBalancer
#  ports:
#    - protocol: TCP
#      port: 80
#      targetPort: 80
#  selector:
#    app: area51-web
