---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: area51-local-pv-3
  labels:
    volume: registry-volume
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: area51-docker-registry-storage
  local:
    path: /mnt/registry
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - init

