---
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: docker-registry
  labels:
    app: registry
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: registry
  ports:
    - name: docker-port
      protocol: TCP
      port: 5000
      targetPort: 30002
---
kind: Service
apiVersion: v1
metadata:
  name: registry-nodeport
  namespace: docker-registry
  labels:
    app: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
  - port: 5000
    nodePort: 30002
    protocol: TCP
