- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  vars_files:
    - host_vars/os_hosts.yaml
  gather_facts: true

  roles:
    - role: openstack-security-group
    - role: openstack-volume
    - role: k3s-deploy-hosts
    
