---
- name: Set hostname
  hostname:
    name: '{{ hostvars[inventory_hostname].openstack.name }}'

- name: Add new hostname to hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ hostvars[inventory_hostname].openstack.name }}'
    state: present

- name: Add peers to file
  lineinfile:
    path: /etc/hosts
    line: '{{ hostvars[item].openstack.accessIPv4 }} {{ hostvars[item].openstack.name }}'
    state: present
  loop: "{{ groups['all'] }}"


