FROM ubuntu:latest

# Install Python3
RUN apt-get -y update
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y


# Install Python3 Packages
RUN pip3 install nltk
RUN pip3 install textblob